# Generated by Django 3.0.1 on 2021-04-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='design',
            field=models.TextField(default=''),
        ),
    ]
