# Generated by Django 3.0.1 on 2021-02-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='design_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
