# Generated by Django 3.0.1 on 2021-05-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0002_auto_20210218_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Design',
        ),
    ]
