# Generated by Django 3.1.2 on 2020-10-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201020_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='svg_height',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='svg_width',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='viewBox_height',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='viewBox_width',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
