# Generated by Django 3.1.2 on 2020-10-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_decoration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bottom_svg_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bottom_svg_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='top_svg_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='top_svg_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
