# Generated by Django 3.1.2 on 2020-11-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201030_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
