# Generated by Django 3.1.2 on 2020-11-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_delete_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decoration',
            name='href',
        ),
        migrations.AddField(
            model_name='decoration',
            name='decoration_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
