# Generated by Django 3.1.2 on 2020-11-03 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201102_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('icon_full', models.ImageField(null=True, upload_to='')),
                ('icon_top', models.ImageField(null=True, upload_to='')),
                ('icon_bottom', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.icon'),
        ),
    ]
