# Generated by Django 3.1.2 on 2020-11-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201103_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='viewBox_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='viewBox_width',
        ),
    ]
