# Generated by Django 3.1.2 on 2020-11-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201104_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decoration',
            old_name='sku',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pattern',
            old_name='sku',
            new_name='name',
        ),
    ]
